services:
  AuthRBAC_db:
    image: postgres:16
    container_name: 'authRBAC-db'
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "15432:5432"
